name: Run tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install test dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install .[test]
    - name: Install nbformat
      run: |
        pip install .
        pip freeze
    - name: List dependencies
      run: pip list
    - name: Run tests
      run: pytest ipypandex/tests -v
